config/routes.rb
Rails.application.routes.draw do
  resources :groups do
    resources :events
    resources :athletes
  end
  resources :sports
  resources :people
  devise_for :users
  get 'home/index'
  resources :home
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sport.rb
class Sport < ApplicationRecord
  has_attached_file :foto, styles: {large: "600x600", medium: "300x300>", thumb: "100x100>" }, default_url: "padrao.jpg"
  validates_attachment_content_type :foto, content_type: /\Aimage\/.*\z/
  has_many :groups
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :set_sport, only: [:show, :edit, :update, :destroy]

  # GET /sports
  # GET /sports.json
  def index
    @sports = Sport.all
  end

  # GET /sports/1
  # GET /sports/1.json
  def show
  end

  # GET /sports/new
  def new
    @sport = Sport.new
  end

  # GET /sports/1/edit
  def edit
  end

  # POST /sports
  # POST /sports.json
  def create
    @sport = Sport.new(sport_params)

    respond_to do |format|
      if @sport.save
        format.html { redirect_to @sport, notice: 'Sport was successfully created.' }
        format.json { render :show, status: :created, location: @sport }
      else
        format.html { render :new }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sports/1
  # PATCH/PUT /sports/1.json
  def update
    respond_to do |format|
      if @sport.update(sport_params)
        format.html { redirect_to @sport, notice: 'Sport was successfully updated.' }
        format.json { render :show, status: :ok, location: @sport }
      else
        format.html { render :edit }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sports/1
  # DELETE /sports/1.json
  def destroy
    @sport.destroy
    respond_to do |format|
      format.html { redirect_to sports_url, notice: 'Sport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sport
      @sport = Sport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sport_params
      params.require(:sport).permit(:nome, :descricao, :regra, :foto)
    end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/_form.html.erb
<div class="form-new">
<%= form_with(model: sport, local: true, :html => {multipart: true}) do |form| %>
  <% if sport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sport.errors.count, "error") %> prohibited this sport from being saved:</h2>

      <ul>
      <% sport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :sport_nome, autofocus: true, type:"text", id:"inputNome",class:"form-control", placeholder:"Ex: Futebol", required:'autofocus' , autocomplete: "nome"%>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_area :descricao, id: :sport_descricao , autofocus: true, type:"text_area", id:"inputDescricao",class:"form-control", placeholder:"Breve descrição do esporte", autocomplete: "descricao", required:'autofocus' %>
  </div>

  <div class="field">
    <%= form.label :regra %>
    <%= form.text_area :regra, id: :sport_regra, autofocus: true, type:"text_area", id:"inputRegra",class:"form-control", placeholder:"Regras do esporte", autocomplete: "regra" , required:'autofocus' %>
  </div>
  <div class="field">
    <%= form.label :foto %>
    <%= form.file_field :foto%>
  </div>

  <div class="actions">
   <br> <%= form.submit "Salvar", class:"btn btn-lg btn-primary btn-block" %>
  </div>
</div>

<% end %>

app/views/sports/edit.html.erb
<div class="jumbotron">
 <div class="container">
	 <div class="alert alert-info" style="margin-top:10px; text-align: center;">
       		<h1><span>Editar Esporte</span></h1>
      </div>

		<%= render 'form', sport: @sport %>
		
		<section class="form-new">
		 <%= link_to 'Detalhes', @sport, class:"btn btn-lg btn-success btn-block" %> 
		 <%= link_to 'Voltar', sports_path,  class:"btn btn-lg btn-danger btn-block" %>
		</section>
	</div>
</div>

app/views/sports/index.html.erb
<div class="jumbotron">
 <div class="container">
    <% if notice == " " %>
     <div class="alert alert-warning fade in alert-dismissable">
        <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
        <strong><p id="notice"><%= notice %></p></strong>
      </div>
    <% end -%>

     <div class="alert alert-info" style="margin-top:10px; text-align: center;">
          <h1><span>Esportes</span></h1>
      </div>
       <section class="form-new">
    <%= link_to 'Novo Esporte', new_sport_path, class:"btn btn-lg btn-primary btn-block" %>
  </section>

    <div class="row placeholders">
        <% @sports.each do |sport| %>
        
           <div class="col-xs-6 col-sm-3 placeholder">
            <img class="rounded-circle" src="<%= image_url sport.foto.url(:large) %>" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4><%= sport.nome %></h4>
              <span class="text-muted"><%= sport.descricao %></span><br>
              
               <%= link_to 'Detalhes', sport, class:"btn  btn-success" %>
               <%= link_to 'Edit', edit_sport_path(sport), class:"btn  btn-primary" %>
               <%= link_to 'Excluir', sport,class:"btn  btn-danger", method: :delete, data: { confirm: 'Confirma exclusão?' } %>
            </div>
        <% end %>
    </div>

  </div>
</div>

app/views/sports/new.html.erb
<div class="jumbotron">
 <div class="container">
	 <div class="alert alert-info" style="margin-top:10px; text-align: center;">
       		<h1><span>Novo Esporte</span></h1>
      </div>

		<%= render 'form', sport: @sport %>

		<section class="form-new">
		<%= link_to 'Voltar', sports_path, class:"btn btn-lg btn-danger btn-block" %>
		</section>
	</div>
</div>

app/views/sports/show.html.erb
<div class="jumbotron">
 <div class="container">
    <% if notice == " " %>
     <div class="alert alert-warning fade in alert-dismissable">
        <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
        <strong><p id="notice"><%= notice %></p></strong>
      </div>
    <% end -%>

     <div class="alert alert-info" style="margin-top:10px; text-align: center;">
          <h1><span>Esporte <%= @sport.nome %></span></h1>
      </div>
      <section class="text-center">
      <img src="<%= image_url @sport.foto.url(:large) %>" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
      </section><br>
      <section> 
        <p>
		  <strong>Nome:</strong>
		  <%= @sport.nome %>
		</p>

		<p>
		  <strong>Descricao:</strong>
		  <%= @sport.descricao %>
		</p>

		<p>
		  <strong>Regra:</strong>
		  <%= @sport.regra %>
		</p>

		<section class=" text-center">
			<%= link_to 'Editar', edit_sport_path(@sport), class:"btn  btn-primary" %>
			<%= link_to 'Voltar', sports_path, class:"btn  btn-danger" %>
		</section>
  <!--  <%= image_tag @sport.foto.url(:large) %>
		<%= image_tag @sport.foto.url(:medium) %>
		<%= image_tag @sport.foto.url(:thumb) %> -->

	  </section>
	</div>
</div>