config/routes.rb
Rails.application.routes.draw do
  resources :groups do
    resources :events
    resources :athletes
  end
  resources :sports
  resources :people
  devise_for :users
  get 'home/index'
  resources :home
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :sport
  belongs_to :fundador, class_name: "Person"
  has_many :athletes
  has_many :events
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]


  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @athletes = @group.athletes
    @event = Event.new
    @event.group = @group
  end

  # GET /groups/new
  def new
    @group = Group.new
    if current_user.person.nil? == true
      redirect_to new_person_path
    end
    @group.fundador = current_user.person
    @esportes = Sport.all
  end

  # GET /groups/1/edit
  def edit
    @esportes = Sport.all
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Grupo criado com sucesso.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Grupo atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Grupo excluido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:nome, :descricao, :sport_id, :fundador_id, :estatuto)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
 <div class="form-new">
  <%= form_with(model: group, local: true) do |form| %>
    <% if group.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

        <ul>
          <% group.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :nome %>
      <%= form.text_field :nome, id: :group_nome , class: "form-control"%>
    </div>

    <div class="form-group">
      <%= form.label :descricao %>
      <%= form.text_field :descricao, id: :group_descricao, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label "Atividade Esportiva" %>
      <%= form.select :sport_id, options_from_collection_for_select(@esportes, "id", "nome"), class: "form-control" %>
    </div>

    <div class="form-group">
      <label for="group_fundador_id">Fundador</label>
      <p><%= @group.fundador.nome %></p>
    </div>

    <div class="form-group">
      <%= form.label :estatuto %>
      <%= form.text_area :estatuto, id: :group_estatuto, class: "form-control" %>
    </div>
    <div style="visibility:hidden" class="form-group ">
      <%= form.label :fundador_id %>
      <%= form.text_field :fundador_id, id: :group_fundador_id , class: "form-control hiddden"%>
    </div>
    <div class="actions" >
      <%= form.submit "Salvar",  class:"btn btn-lg btn-primary btn-block" %>
    </div>

  <% end %>
</div>

app/views/groups/edit.html.erb
<div class="jumbotron">
 <div class="container">
	 <div class="alert alert-info" style="margin-top:10px; text-align: center;">
       		<h1><span>Editar Grupo</span></h1>
      </div>

		<%= render 'form', group: @group %>

		<section class="form-new">
		 <%= link_to 'Detalhes', @group, class:"btn btn-lg btn-success btn-block" %> 
		 <%= link_to 'Voltar', groups_path,  class:"btn btn-lg btn-danger btn-block" %>
		</section>
	</div>
</div>

app/views/groups/index.html.erb
<div class="jumbotron">
 <div class="container">
    <% if notice == " " %>
     <div class="alert alert-warning fade in alert-dismissable">
        <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
        <strong><p id="notice"><%= notice %></p></strong>
      </div>
    <% end -%>

     <div class="alert alert-info" style="margin-top:10px; text-align: center;">
          <h1><span>Grupos</span></h1>
      </div>
       <section class="form-new">
        <%= link_to 'Novo Grupo', new_group_path, class:"btn btn-lg btn-primary btn-block" %>
       </section>

    <div class="row placeholders">
    <% @groups.each do |group| %>
     
       <div class="col-xs-6 col-sm-3 placeholder">
            <img class="rounded-circle" src="<%= image_path("padrao2.png")%>" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4><%= group.nome %></h4>
             <label>Descrição:</label> 
                <span class="text-muted"><%= group.descricao %></span><br>
             <label>Esporte:</label>
              <span class="text-muted"><%= group.sport.nome %></span><br>
              
               <%= link_to 'Detalhes', group, class:"btn  btn-success" %>
               <%= link_to 'Edit', edit_group_path(group), class:"btn  btn-primary" %>
               <%= link_to 'Excluir', group,class:"btn  btn-danger", method: :delete, data: { confirm: 'Confirma exclusão?' } %>
            </div>
    <% end %>

    </div>

  </div>
</div>

app/views/groups/new.html.erb
<div class="jumbotron">
	<div class="container">

		<div class="alert alert-info" style="margin-top:10px; text-align: center;">
       		<h1><span>Novo Grupo de Peladeiros</span></h1>
      </div>

  <%= render 'form', group: @group %>

  
  <section class="form-new">
		<%= link_to 'Voltar', groups_path, class:"btn btn-lg btn-danger btn-block" %>
		</section>
	</div>
</div>

app/views/groups/show.html.erb
<div class="jumbotron">
 <div class="container">
    <% if notice == " " %>
     <div class="alert alert-warning fade in alert-dismissable">
        <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
        <strong><p id="notice"><%= notice %></p></strong>
      </div>
    <% end -%>

     <div class="alert alert-info" style="margin-top:10px; text-align: center;">
          <h1><span>Grupo <%= @group.nome %></span></h1>
      </div>
        <ul class="nav nav-tabs">
          <li role="presentation" class="active">
            <a href="#home" class="alert alert-info" data-toggle="tab">Dashboard</a>
          </li>
          <li role="presentation">
            <a href="#atletas" class="alert alert-danger" data-toggle="tab">Peladeiros</a>
          </li>
        <li role="presentation">
           <a href="#eventos" class="alert alert-success" data-toggle="tab" id="clickEvent">Eventos</a>
             <script type="application/javascript">
              $('#clickEvent').on('shown.bs.tab' , function () {
               $('#calendar').fullCalendar({
                header: {
                    center: 'month,agendaFourDay,agendaWeek' // buttons for switching between views
                },
                views: {
                    agendaFourDay: {
                        type: 'agenda',
                        duration: { days: 4 },
                        buttonText: '4 dias'
                    }
                },
                events: '/groups/<%= @group.id %>/events.json',
                timeFormat: 'HH(:mm)'
                }
            );
        });


      </script>
    </li>
  </ul>
  <div class="tab-content">
    <div id="home" class="tab-pane fade in active">
      <p>
        <strong>Nome:</strong>
        <%= @group.nome %>
      </p>

      <p>
        <strong>Descricao:</strong>
        <%= @group.descricao %>
      </p>

      <p>
        <strong>Esporte:</strong>
        <%= @group.sport.nome %>
      </p>

      <p>
        <strong>Fundador:</strong>
        <%= @group.fundador.nome %>
      </p>

      <p>
        <strong>Estatuto:</strong>
        <%= @group.estatuto %>
      </p>
       <%= link_to 'Editar', edit_group_path(@group), class:"btn  btn-primary" %> 
      <%= link_to 'Voltar', groups_path, class:"btn  btn-danger" %>
    </div>
    <div id="atletas" class="tab-pane fade">
      <div class="row">
        <%= link_to "<span class='glyphicon glyphicon-plus' aria-hidden='true'>Peladeiro</span>".html_safe, new_group_athlete_path(@group), class:"btn btn-primary"  %>
      </div>
      <div class="row">
        <%= render @athletes %>
      </div>
    </div>
    <div id="eventos" class="tab-pane fade">
      <!-- Button trigger modal -->
      <div class="row">
        <button type="button" class="btn btn-primary " data-toggle="modal" data-target="#myModal">
        <span class="glyphicon glyphicon-plus " aria-hidden="true">Eventos</span>
        </button>
      </div>
      <div class="row">
        <div class="col-md-6">
          <table class="table table-striped">
            <thead>
            <tr>
              <th>Descrição</th>
              <th>Data</th>
              <th>Local</th>
            </tr>
            </thead>
            <tbody id="eventsTR">
              <% @group.events.each do |event| %>
              <tr id="event_<%= event.id %>">
                <td><%= event.descricao %></td>
                <td><%= event.start_time %></td>
                <td><%= event.local %></td>
                <td><%= link_to 'Detalhes', group_event_path(@group,event), class:"btn  btn-success" %></td>
                <% if @group.fundador.user == (current_user) %>
                  <td><%= link_to 'Editar', edit_group_event_path(@group,event), class:"btn  btn-primary" %></td>
                  <td><%= link_to 'Excluir',[@group,event], class:"btn  btn-danger", method: :delete,
                                  data: { confirm: 'Confirma exclusão?' }, remote: true %></td>
                <% end %>
              </tr>

              <% end %>

            </tbody>
          </table>
        </div>
        <div class="col-md-6">

          <div id="calendar"></div>
        </div>

      </div>

    </div>

  </div>

</div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Cadastro de Evento</h4>
      </div>
      <div class="modal-body">
        <%= form_with(model: [@group,@event], local: false) do |form| %>
          <% if @event.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

              <ul>
                <% @event.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= form.label "Descrição" %>
            <%= form.text_field :descricao, class: "form-control" ,id: :event_descricao %>
          </div>

          <div class="col-sd-5">

            <%= form.label "Data/Hora Início" %>
            <div class='input-group date' id='datetimepicker1'>
              <%= form.text_field  :start_time, class: "form-control" ,id: :event_start_time %>
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
          </div>


          <div class="form-group">
            <%= form.label "Data/Hora Fim" %>
            <div class='input-group date' id='datetimepicker2'>
              <%= form.text_field  :end_time, class: "form-control" ,id: :event_end_time %>
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
          </div>

          <div class="form-group">
            <%= form.label :local %>
            <%= form.text_field :local,class: "form-control", id: :event_local %>
          </div>

          <div class="hidden">
            <%= form.label :group_id %>
            <%= form.text_field :group_id, id: :event_group_id %>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            <button type="submit" class="btn btn-primary">
              <%= @event.id.nil? ? 'Cadastrar' : 'Editar' %>
            </button>
          </div>
      <% end %>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker(
                    {
                        stepping: 15,
                        sideBySide: true
                    }
                );
                $('#datetimepicker2').datetimepicker({
                    stepping: 15,
                    sideBySide: true,
                    useCurrent: false  //Important! See issue #1075
                });
                $("#datetimepicker1").on("dp.change", function (e) {
                    $('#datetimepicker2').data("DateTimePicker").minDate(e.date);
                });
                $("#datetimepicker2").on("dp.change", function (e) {
                    $('#datetimepicker1').data("DateTimePicker").maxDate(e.date);
                });
            });
        </script>
      </div>
    </div>
  </div>
</div>