config/routes.rb
Rails.application.routes.draw do
  resources :groups do
    resources :events
    resources :athletes
  end
  resources :sports
  resources :people
  devise_for :users
  get 'home/index'
  resources :home
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/athlete.rb
class Athlete < ApplicationRecord
  belongs_to :person
  belongs_to :group
  enum status: { pendente: 0, ativo: 1, inativo: 2, suspenso: 3, afastado: 4 }
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  before_action :set_athlete, only: [:show, :edit, :update, :destroy]
  before_action :get_group

  def get_group
    @group = Group.find(params[:group_id])
  end

  # GET /athletes
  # GET /athletes.json
  def index
    @athletes = Athlete.all
  end

  # GET /athletes/1
  # GET /athletes/1.json
  def show
  end

  # GET /athletes/new
  def new
    @athlete = Athlete.new
    if current_user.person.nil? == true
      redirect_to new_person_path , notice: 'Complete seu cadastro antes de se cadastrar como um atleta.'
    end
    @athlete.group = @group
    @athlete.person = current_user.person

  end

  # GET /athletes/1/edit
  def edit
  end

  # POST /athletes
  # POST /athletes.json
  def create
    @athlete = Athlete.new(athlete_params)

    respond_to do |format|
      if @athlete.pendente!
        format.html { redirect_to [@group,@athlete], notice: 'Atleta criado com sucesso.' }
        format.json { render :show, status: :created, location: [@group,@athlete] }
      else
        format.html { render :new }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /athletes/1
  # PATCH/PUT /athletes/1.json
  def update
    respond_to do |format|
      if @athlete.update(athlete_params)
        format.html { redirect_to [@group,@athlete], notice: 'Atleta atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: [@group,@athlete] }
      else
        format.html { render :edit }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /athletes/1
  # DELETE /athletes/1.json
  def destroy
    @athlete.destroy
    respond_to do |format|
      format.html { redirect_to group_athletes_url, notice: 'Ateta excluido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_athlete
      @athlete = Athlete.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def athlete_params
      params.require(:athlete).permit(:score, :status, :person_id, :group_id)
    end
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/views/athletes/_athlete.html.erb
<div class="col-xs-6 col-sm-3 placeholder" id="athlete_<%= athlete.id %>">

  <h4><%= athlete.person.nome %></h4>
  <label>Score:</label>
  <span class="text-muted"><%= athlete.score %></span><br>
  <label>Status:</label>
  <span class="text-muted"><%= athlete.status %></span><br>

  <%= link_to 'Detalhes', [@group,athlete], class:"btn  btn-success" %>
  <%= link_to 'Edit', edit_group_athlete_path(@group,athlete), class:"btn  btn-primary" %>
  <%= link_to 'Excluir', [@group,athlete],class:"btn  btn-danger", method: :delete, data: { confirm: 'Confirma exclusão?' } %>
</div>

app/views/athletes/_form.html.erb
<div class="form-new">
<%= form_with(model: [@group,athlete], local: true) do |form| %>
  <% if athlete.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(athlete.errors.count, "error") %> prohibited this athlete from being saved:</h2>

      <ul>
      <% athlete.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :score %>
    <%= form.text_field :score, id: :athlete_score,class:"form-control" %>
  </div>
    <% if @group.fundador.user == current_user %>
      <div class="field">
        <%= form.label :status %>
        <%= form.select(:status, Athlete.statuses.keys.map {|key| [key.humanize, key]},
                        id: :athlete_status,class:"form-control",
                        include_blank: true) %>
      </div>
    <%end %>

  <div class="field">
    <%= form.label :person_id %>
    <%= form.text_field :person_id, id: :athlete_person_id,class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.text_field :group_id, id: :athlete_group_id,class:"form-control" %>
  </div>

 <div class="actions">
   <br> <%= form.submit "Salvar", class:"btn btn-lg btn-primary btn-block" %>
  </div>
<% end %>
</div>

app/views/athletes/edit.html.erb
<h1>Editing Athlete</h1>

<%= render 'form', athlete: @athlete %>

<%= link_to 'Show', [@group,@athlete] %> |
<%= link_to 'Back', group_athletes_path(@group) %>

app/views/athletes/index.html.erb
<div class="jumbotron">
 <div class="container">
   <% if flash[:notice] %>
     <div class="alert alert-info">
       <button type="button" class="close" data-dismiss="alert" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
       <%= notice %>
     </div>
   <% end %>

     <div class="alert alert-info" style="margin-top:10px; text-align: center;">
          <h1><span>Peladeiros - <%= @group.nome %></span></h1>
      </div>
       <section class="form-new">
    <%= link_to 'Novo Atleta', new_group_athlete_path(@group), class:"btn btn-lg btn-primary btn-block" %>
  </section>

    <div class="row placeholders">
    <% @athletes.each do |athlete| %>
    <div class="col-xs-6 col-sm-3 placeholder">
           
              <h4><%= athlete.person.nome %></h4>
              <label>Score:</label>
                  <span class="text-muted"><%= athlete.score %></span><br>
              <label>Status:</label>
                  <span class="text-muted"><%= athlete.status %></span><br>

               <%= link_to 'Detalhes', [@group,athlete], class:"btn  btn-success" %>
               <%= link_to 'Edit', edit_group_athlete_path(@group,athlete), class:"btn  btn-primary" %>
               <%= link_to 'Excluir', [@group,athlete],class:"btn  btn-danger", method: :delete, data: { confirm: 'Confirma exclusão?' } %>
            </div>
        <% end %>
    </div>

  </div>
</div>

app/views/athletes/new.html.erb
<div class="jumbotron">
 <div class="container">
	 <div class="alert alert-info" style="margin-top:10px; text-align: center;">
       		<h1><span>Novo Cadastro</span></h1>
      </div>

			<%= render 'form', athlete: @athlete %>

			<section class="form-new">
		<%= link_to 'Voltar', [@group,@athlete], class:"btn btn-lg btn-danger btn-block" %>
		</section>
	</div>
</div>

app/views/athletes/show.html.erb
<div class="jumbotron">
 <div class="container">
    <% if notice == " " %>
     <div class="alert alert-warning fade in alert-dismissable">
        <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
        <strong><p id="notice"><%= notice %></p></strong>
      </div>
    <% end -%>

     <div class="alert alert-info" style="margin-top:10px; text-align: center;">
          <h1><span>Detalhes do Atleta <%= @athlete.person.nome %></span></h1>
      </div><br>
       <section> 
			<p>
			  <strong>Score:</strong>
			  <%= @athlete.score %>
			</p>

			<p>
			  <strong>Status:</strong>
			  <%= @athlete.status %>
			</p>

			<p>
			  <strong>Person:</strong>
			  <%= @athlete.person %>
			</p>

			<p>
			  <strong>Group:</strong>
			  <%= @athlete.group %>
			</p>
		<section class=" text-center">
			<%= link_to 'Editar',edit_group_athlete_path(@group,@athlete), class:"btn  btn-primary" %>
			<%= link_to 'Voltar',@group, class:"btn  btn-danger" %>
		</section>

	  </section>
	</div>
</div>