config/routes.rb
Rails.application.routes.draw do
  resources :groups do
    resources :events
    resources :athletes
  end
  resources :sports
  resources :people
  devise_for :users
  get 'home/index'
  resources :home
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :group
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :get_group

  def get_group
    @group = Group.find(params[:group_id])
  end

  # GET /events
  # GET /events.json
  def index
    if params[:group_id].nil?
      @events = Event.all
    else
      @events = @group.events
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
    @event.group = @group
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create

    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to [@group,@event], notice: 'Evento criado com sucesso.' }
        format.json { render :show, status: :created, location: @event }
        format.js
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to [@group,@event], notice: 'Evento atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to @group, notice: 'O evento foi removido com sucesso.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:descricao, :start_time, :end_time, :local, :group_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="form-new">
<%= form_with(model: [@group,event], local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group ">
    <%= form.label :descricao %>
    <%= form.text_field :descricao, id: :event_descricao, class: "form-control" %>
  </div>

  <div class="form-group ">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time, id: :event_start_time, class: "form-control" %>
  </div>

  <div class="form-group ">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time, id: :event_end_time, class: "form-control" %>
  </div>

  <div class="form-group ">
    <%= form.label :local %>
    <%= form.text_field :local, id: :event_local, class: "form-control" %>
  </div>

  <div style="visibility:hidden" class="form-group ">
    <%= form.label :group_id %>
    <%= form.text_field :group_id, id: :event_group_id, class: "form-control hiddden" %>
  </div>

  <div class="actions" >
      <%= form.submit "Salvar",  class:"btn btn-lg btn-primary btn-block" %>
    </div>
<% end %>
</div>

app/views/events/create.js.erb
$("#myModal").modal('hide');
$("#eventsTR").append("<tr id='event_<%= @event.id %>'>"+
    "<td><%= @event.descricao %></td>"+
    "<td><%= @event.start_time %></td>"+
    "<td><%= @event.local %></td>"+
    "</tr>").fadeIn();
// location.reload();

app/views/events/destroy.js.erb
$("#<%=dom_id(@event) %>").fadeOut();

app/views/events/edit.html.erb
<div class="jumbotron">
 <div class="container">
	 <div class="alert alert-info" style="margin-top:10px; text-align: center;">
       		<h1><span>Editar Evento</span></h1>
      </div>

		<%= render 'form', event: @event %>
		<section class="form-new">
		 <%= link_to 'Detalhes', [@group,@event], class:"btn btn-lg btn-success btn-block" %> 
		 <%= link_to 'Voltar', group_events_path(@group),  class:"btn btn-lg btn-danger btn-block" %>
		</section>
	</div>
</div>

app/views/events/index.html.erb
<div class="jumbotron">
 <div class="container">
   <% if flash[:notice] %>
     <div class="alert alert-info">
       <button type="button" class="close" data-dismiss="alert" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
       <%= notice %>
     </div>
   <% end %>

     <div class="alert alert-info" style="margin-top:10px; text-align: center;">
          <h1><span>Eventos</span></h1>
      </div>
       <section class="form-new">
        <%= link_to 'Novo Evento', new_group_event_path, class:"btn btn-lg btn-primary btn-block" %>
       </section>

    <div class="row placeholders">
      <div class="row" >
        <% @events.each do |event| %>
            <div class="col-xs-6 col-sm-3" id="event_<%= event.id %>">
               <div class="card mb-4 box-shadow text-white bg-info">
                <div class="card-header">
                  <h2 class="card-title">Descrição:</h2>
                  <h5 class="my-0 font-weight-normal"><%= event.descricao %></h5>
                </div>
              <div class="card-body">
                 <h2 class="card-title">Custos:</h2>
                <h1 class="card-title pricing-card-title">R$ <small class="text-muted"> 50.00</small></h1>
                <ul class="list-unstyled mt-3 mb-4">

                  <li><label>Local: </label><%= event.local %></li>
                  <li><label> Grupo:</label><%= event.group.nome %></li>
                  <h3 class="card-title">Período de inscrição:</h3>
                  <li><label>Inicio:</label><%= event.start_time %> </li>
                  <li><label>Fim: </label><%= event.end_time %></li>
                </ul>
                <button type="button" class="btn btn-lg btn-block btn-primary">Participar</button><br>
                <section>
                
                 <%= link_to 'Detalhes', [@group,event], class:"btn  btn-success"  %>
                 <%= link_to 'Editar', edit_group_event_path(@group,event), class:"btn  btn-primary" %>
                <%= link_to 'Excluir', [@group,event],class:"btn  btn-danger", method: :delete, data: { confirm: 'Confirma esclusão?' }, remote: true %>
                </section>
              </div>
            </div>
          </div>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="jumbotron">
	<div class="container">

		<div class="alert alert-info" style="margin-top:10px; text-align: center;">
       		<h1><span>Novo Evento</span></h1>
      </div>

			<%= render 'form', event: @event %>
 		<section class="form-new">
			<%= link_to 'Voltar', group_events_path(@group), class:"btn btn-lg btn-danger btn-block" %>
		</section>
	</div>
</div>

app/views/events/show.html.erb
<div class="jumbotron">
<div id="container-fluid">

  <% if flash[:notice] %>
    <div class="alert alert-info">
      <button type="button" class="close" data-dismiss="alert" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
      <%= notice %>
    </div>
  <% end %>

  <div class="panel panel-primary">
    <div class="panel-heading h3"><%= @event.group.nome %> - Pelada do dia <%= @event.start_time.to_formatted_s(:short)  %></div>
    <div class="panel-body">
      <div class="row">
         <div class="alert alert-info" style="margin-top:10px; text-align: center;">
          <h1><span>Escalação da equipe</span></h1>
      </div>
        <div class="pitch">
          <span class="help">Arraste os jogadores</span>
          <ul id="goal" class="container">
            <li>
              <span class="number">1</span>
              <span class="name">Hart</span>
            </li>
          </ul>
          <ol id="defence" class="container">
            <li>
              <span class="number">2</span>
              <span class="name">Walker</span>
            </li>
            <li>
              <span class="number">5</span>
              <span class="name">Cahill</span>
            </li>
            <li>
              <span class="number">6</span>
              <span class="name">Stones</span>
            </li>
            <li>
              <span class="number">3</span>
              <span class="name">Rose</span>
            </li>
          </ol>
          <ol id="midfield" class="container">
            <li>
              <span class="number">8</span>
              <span class="name">Henderson</span>
            </li>
            <li>
              <span class="number">4</span>
              <span class="name">Dier</span>
            </li>
            <li>
              <span class="number">10</span>
              <span class="name">Rooney</span>
            </li>
          </ol>
          <ol id="attack" class="container">
            <li>
              <span class="number">7</span>
              <span class="name">Sterling</span>
            </li>
            <li>
              <span class="number">9</span>
              <span class="name">Kane</span>
            </li>
            <li>
              <span class="number">11</span>
              <span class="name">Lallana</span>
            </li>
          </ol>
        </div>
        <div class="bench">
          <span class="help">Subs</span>
          <ul id="subs" class="container">
            <li>
              <span class="number">12</span>
              <span class="name">Smalling</span>
            </li>
            <li>
              <span class="number">13</span>
              <span class="name">Heaton</span>
            </li>
            <li>
              <span class="number">14</span>
              <span class="name">Walcott</span>
            </li>
            <li>
              <span class="number">15</span>
              <span class="name">Sturridge</span>
            </li>
            <li>
              <span class="number">16</span>
              <span class="name">Jagielka</span>
            </li>
            <li>
              <span class="number">18</span>
              <span class="name">Drinkwater</span>
            </li>
            <li>
              <span class="number">20</span>
              <span class="name">Alli</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
      <div id="row">
        <div class="col-md-6">
          <div class="panel panel-info">
            <div class="panel-heading h4">Atletas confirmados</div>
            <div class="panel-body">
            </div>
            <div class="panel-footer">
              <div>Convidados</div>
              <ul>
                <li>Amigos...</li>
                <li>Amigos...</li>
                <li>Amigos...</li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="panel panel-success">
            <div class="panel-heading h4">Jogos</div>
            <div class="panel-body">

            </div>
          </div>
        </div>
      </div>
      <div id="row">
        <div class="col-md-12">
          <div class="panel panel-success">
            <div class="panel-body">
                <p>
                <strong>Group:</strong>
                <%= @event.group.nome %>
              </p>
              <strong>Descricao:</strong>
               <p> <%= @event.descricao %></p>
               <p>
                <strong>Local:</strong>
                <%= @event.local %>
              </p>
              <%= link_to 'Editar', edit_group_event_path(@group,@event), class:"btn  btn-primary" %> 
              <%= link_to 'Voltar', group_events_path(@group), class:"btn btn-danger" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div> 
</div>

<script type="application/javascript">
    // using Dragula.js

    var drake = dragula({
        containers: [
            document.querySelector('#goal'), document.querySelector('#defence'), document.querySelector('#midfield'),
            document.querySelector('#attack'),
            document.querySelector('#subs')
        ],
        revertOnSpill: true,
        mirrorContainer: document.body,
        ignoreInputTextSelection: true
    });

    // validation
    drake.on('drop', function(el, target, source, sibling) {

        // max 11 players
        if (target.id !== 'subs' && document.querySelectorAll('.pitch li').length > 11) {
            drake.cancel();
        }

        // 1 goalkeeper
        if (target.id === 'goal' && target.children.length > 1) {
            drake.cancel();
        }

        // 5 defenders
        if (target.id === 'defence' && target.children.length > 5) {
            drake.cancel();
        }

        // 5 midfielders
        if (target.id === 'midfield' && target.children.length > 5) {
            drake.cancel();
        }

        // 4 attackers
        if (target.id === 'attack' && target.children.length > 4) {
            drake.cancel();
        }

    });
</script>
<style>
  /* dragula default styles */

  .gu-mirror {
    position: fixed !important;
    margin: 0 !important;
    z-index: 9999 !important;
    opacity: 0.8;
    -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=80)";
    filter: alpha(opacity=80);
  }
  .gu-hide {
    display: none !important;
  }
  .gu-unselectable {
    -webkit-user-select: none !important;
    -moz-user-select: none !important;
    -ms-user-select: none !important;
    user-select: none !important;
  }
  .gu-transit {
    opacity: 0.2;
    -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=20)";
    filter: alpha(opacity=20);
  }

  /* custom CSS */

  /*body {*/
    /*margin:0;*/
    /*overflow:hidden;*/
  /*}*/

  .help {
    color:rgba(255,255,255,.5);
    font-family:sans-serif;
    font-size:3vmin;
  }

  .pitch {
    background-color:#5d9634;
    background: linear-gradient(
        to bottom,
        #5d9634,
        #5d9634 50%,
        #538c2b 50%,
        #538c2b
    );
    background-size: 100% 20vmin;
    padding:1vmin;
  }

  .bench {
    background-color:#006;
    padding:1vmin;
  }

  .container {
    display:flex;
    height:10vmin;
    justify-content:space-around;
    list-style:none;
    margin:6vmin 0;
  }

  .container li,
  .gu-mirror {
    cursor:move;
    cursor: -webkit-grab;
    cursor: -moz-grab;
    cursor: grab;
    height:10vmin;
    list-style:none;
    position:relative;
    width:10vmin;
  }

  .gu-mirror {
    cursor:move;
    cursor: -webkit-grabbing;
    cursor: -moz-grabbing;
    cursor: grabbing;
  }

  .container li .number,
  .gu-mirror .number {
    background-color:#fff;
    color:#c00;
    font-family:sans-serif;
    font-size:4vmin;
    left:2vmin;
    padding:1vmin .5vmin;
    position:absolute;
    right:2vmin;
    text-align:center;
    text-shadow:0 0 1px #fff;
    top:0;
  }

  .container li .number:before,
  .gu-mirror .number:before {
    background-color:#def;
    content:"";
    height:2vmin;
    left:0;
    position:absolute;
    top:0;
    transform:rotate(60deg);
    transform-origin:top left;
    width:2vmin;
  }

  .container li .number:after,
  .gu-mirror .number:after {
    background-color:#def;
    content:"";
    height:2vmin;
    position:absolute;
    right:0;
    top:0;
    transform:rotate(-60deg);
    transform-origin:top right;
    width:2vmin;
  }

  #goal li .number {
    background-color:#060;
    color:#fff;
  }

  #goal li .number:before,
  #goal li .number:after {
    background-color:#050;
  }

  .container li .name,
  .gu-mirror .name {
    bottom:0;
    color:#fff;
    font-family:sans-serif;
    font-size:3vmin;
    left:-5vmin;
    position:absolute;
    right:-5vmin;
    text-align:center;
  }
</style>